sudo: False
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
      - gfortran
      - libatlas-base-dev

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements-2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_wait pip install -r requirements-3.txt; fi
  - pip install flake8

# Ensure `requirements.txt` contains all of the dependencies
# for the scripts and that scripts that only operate on
# command-line arguments can be execute
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then ./.travis-script-2.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./.travis-script-3.sh; fi
